FROM ft-rails:on-build

EXPOSE 3000

CMD ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]

# clone app
# git clone https://bitbucket.org/railstutorial/sample_app_4th_ed.git rails_app

# to build inner image
# docker build -t ft-rails:on-build ft-rails/

# to build image 
# docker build -t ex02 .

# to run
# docker run --rm -it -p 3000:3000 ex02
